# Generated by Django 3.0.3 on 2020-03-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dissertation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iplist',
            name='createdAt',
        ),
        migrations.AddField(
            model_name='iplist',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First name'),
        ),
    ]
